FROM node:20 as build-stage

WORKDIR /surveycat
COPY ./template /surveycat/template

WORKDIR /surveycat/template
RUN yarn cache clean
RUN yarn install --frozen-lockfile
RUN yarn build

FROM nginx as production-stage
RUN mkdir -p /app/surveycat 
COPY --from=build-stage /surveycat/template/build /app/surveycat
COPY ./template/nginx.prod.conf /etc/nginx/nginx.conf

## this that

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]