version: '3.2'
services:
  nginx:
    image: cntzoufras/admin-nginx:${IMAGE_VERSION}
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.prod
      # args:
        # - IMAGE_VERSION=${IMAGE_VERSION}
      args:
        - REACT_APP_API_URL=${REACT_APP_API_URL}
        - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
        - REACT_APP_IMAGE_BASE_URL=${REACT_APP_IMAGE_BASE_URL}
        - NODE_ENV=${NODE_ENV}
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.prod.conf:/etc/nginx/nginx.conf
      - shared_uploads:/var/www/images
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - ./nginx_logs:/var/log/nginx
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
      - REACT_APP_BASE_URL=${REACT_APP_BASE_URL}
      - REACT_APP_IMAGE_BASE_URL=${REACT_APP_IMAGE_BASE_URL}
      - NODE_ENV=${NODE_ENV}

    networks:
      - webnet

networks:
  webnet:
    external: true

volumes:
  shared_uploads:
    external: true

