FROM node:20 as build-stage

# ARG IMAGE_VERSION_
# LABEL version=$IMAGE_VERSION

WORKDIR /surveycat
COPY package.json yarn.lock ./
RUN yarn install --frozen-lockfile
COPY . .
# Copy the .env file created during CI/CD into the container
COPY .env /app/.env

RUN yarn build

FROM nginx:alpine as production-stage
RUN mkdir -p /app/surveycat
COPY --from=build-stage /surveycat/build /app/surveycat
COPY ./nginx.prod.conf /etc/nginx/nginx.conf

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]
